spring:
  application:
    name: spring-cafe

  mustache:
    suffix: .html
    servlet:
      cache: false

  datasource:
    url: 'jdbc:h2:tcp://localhost/~/springcafe'
    driver-class-name: 'org.h2.Driver'
    username: 'sa'
    password: ''
    hikari:
      connection-timeout: 1000
      connection-test-query: SELECT 1


server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


